---
- name: restart apache
  service:
    name: "{{ apache_service }}"
    state: restarted

- name: restart nginx
  service:
    name: "{{ nginx_service }}"
    state: restarted

- name: restart apache
  service:
    name: apache2
    state: restarted
